org: codenations
app: swapitranslate
service: softtekchallenge

stages:
  default:
    params:
      filmsTableName: "film-table-${sls:stage}"
      planetsTableName: "planet-table-${sls:stage}"

provider:
  logs:
    httpApi: true
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [FilmsTable, Arn]
            - Fn::GetAtt: [PlanetsTable, Arn]
  environment:
    FILMS_TABLE: ${param:filmsTableName}
    PLANETS_TABLE: ${param:planetsTableName}

functions:
  filmsApi:
    handler: handler.films
    events:
      - httpApi:
          path: /films
          method: "*"
      - httpApi:
          path: /films/{id}
          method: "*"

  planetsApi:
    handler: handler.planets
    events:
      - httpApi:
          path: /planets
          method: "*"
      - httpApi:
          path: /planets/{id}
          method: "*"

  swapiApi:
    handler: handler.swapi
    events:
      - httpApi:
          path: /swapi/{resource}/{id}
          method: "*"

  translateApi:
    handler: handler.translate
    events:
      - httpApi:
          path: /translate
          method: "*"
      - httpApi:
          path: /translate/{id}
          method: "*"

resources:
  Resources:
    FilmsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: filmId
            AttributeType: N
        KeySchema:
          - AttributeName: filmId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:filmsTableName}
    PlanetsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: planetId
            AttributeType: N
        KeySchema:
          - AttributeName: planetId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:planetsTableName}
